### ISSUE TITLE
feat: realtime collaboration

### ISSUE THREAD

**Issue by Quentin-Guillemin** [wisemapping/wisemapping-frontend#19]
Hello,

I work for @GIP-RECIA and have been contributing to your project since it was posted on GitHub. We're looking to implement a web socket with Yjs on the `@wisemapping/editor` part. I haven't found a way to redefine the [DesignerModel](https://github.com/wisemapping/wisemapping-frontend/blob/main/packages/mindplot/src/components/DesignerModel.ts) `entities` and update the UI.

My idea would be to intercept the `modelUpdate` event and send the changes to a web socket. In the same way, by observing the changes in the web socket, we could update the mind map without triggering the web socket.

Can you tell me how I should go about this, so that I can get the most out of your project?

**Comment by Quentin-Guillemin** [comment]
@veigap Can you help me ?

**Comment by veigap** [comment]
Hi Quentin,

Love to have people willing to contribute to the project. My question is, what is the end goal that you are trying to achieve ?

If the goal is concurrent edition support, all the changes performed in a map are performed through [commands](https://github.com/wisemapping/wisemapping-frontend/tree/main/packages/mindplot/src/components/commands). This should be the right place to start. 

As part of that, there are additional events that will need to be that might be worth providing feedback. Eg. If there is node to be edited, block the edition to other people.

Paulo
